title: Abarna Sivaprakasam
logo: /assets/img/headshot_circle.png
description: Turning data into impactful insights — explore my journey of analytical excellence
show_downloads: true
theme: jekyll-theme-minimal
